---
version: 6.0.0
slug: configurator
name: File editor
description: Simple browser-based file editor for Home Assistant
url: https://github.com/home-assistant/addons/tree/master/configurator
arch:
  - aarch64
  - amd64
homeassistant: 0.91.1
homeassistant_api: true
image: homeassistant/{arch}-addon-configurator
ingress: true
init: false
map:
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  dirsfirst: false
  enforce_basepath: true
  git: true
  ignore_pattern:
    - __pycache__
    - .cloud
    - .storage
    - deps
  ssh_keys: []
panel_icon: mdi:wrench
schema:
  dirsfirst: bool
  enforce_basepath: bool
  git: bool
  ignore_pattern:
    - str
  ssh_keys:
    - str
modbus:
  - name: "SAJ_H1"
    type: tcp
    host: 192.168.10.118  # ← CAMBIA esto por la IP de tu AIO3
    port: 502
    sensors:
      - name: "SAJ H1 Potencia Actual"
        unit_of_measurement: "W"
        address: 3004
        input_type: input

      - name: "SAJ H1 Energía Hoy"
        unit_of_measurement: "kWh"
        address: 3014
        input_type: input

      - name: "SAJ H1 Voltaje AC"
        unit_of_measurement: "V"
        address: 3033
        input_type: input

      - name: "SAJ H1 Frecuencia AC"
        unit_of_measurement: "Hz"
        address: 3034
        input_type: input

      - name: "SAJ H1 Temperatura"
        unit_of_measurement: "°C"
        address: 3041
        input_type: input
